CREATE TABLE employees_test(
ID INT PRIMARY KEY NOT NULL,
NAME TEXT NOT NULL,
AGE INT NOT NULL,
ADDRESS CHAR(50),
SALARY REAL);

CREATE TABLE audit(
EMP_no INT NOT NULL,
NAME TEXT NOT NULL);

# 构造触发器
CREATE TRIGGER audit_log AFTER INSERT
    ON employees_test FOR EACH ROW
BEGIN
    INSERT INTO audit VALUES(NEW.ID,NEW.NAME);
END;